const SYSTEM_BASE = "/System";
const CATALOG_BASE = "/Catalog";
const BUSINESS_BASE = "/Business";
const FILE_BASE = "/File";

export const API_ENDPOINTS = {
  System: {
    User: {
      GET_LIST: `${SYSTEM_BASE}/User/get-list`,
      GET_BY_ID: `${SYSTEM_BASE}/User/get-by-id`,
      INSERT: `${SYSTEM_BASE}/User/insert`,
      UPDATE: `${SYSTEM_BASE}/User/update`,
      DELETE_LIST: `${SYSTEM_BASE}/User/delete-list`,
      GET_CURRENT_USER: `${SYSTEM_BASE}/User/get-current-user`,
      GET_ALL_COMBOBOX: `${SYSTEM_BASE}/User/get-all-combobox`,
      EDIT_PROFILE: `${SYSTEM_BASE}/User/edit-profile`,
      CHANGE_PASSWORD: `${SYSTEM_BASE}/User/change-password`,
    },
    SystemGroup: {
      GET_LIST: `${SYSTEM_BASE}/SystemGroup/get-list`,
      GET_BY_ID: `${SYSTEM_BASE}/SystemGroup/get-by-id`,
      INSERT: `${SYSTEM_BASE}/SystemGroup/insert`,
      UPDATE: `${SYSTEM_BASE}/SystemGroup/update`,
      DELETE_LIST: `${SYSTEM_BASE}/SystemGroup/delete-list`,
      GET_ALL_COMBOBOX: `${SYSTEM_BASE}/SystemGroup/get-all-combobox`,
      GET_ALL_NOT_PARENT_COMBOBOX: `${SYSTEM_BASE}/SystemGroup/get-all-not-parent-combobox`,
      GET_ALL: `${SYSTEM_BASE}/SystemGroup/get-all`,
    },
    Menu: {
      GET_LIST: `${SYSTEM_BASE}/Menu/get-list`,
      GET_BY_ID: `${SYSTEM_BASE}/Menu/get-by-id`,
      INSERT: `${SYSTEM_BASE}/Menu/insert`,
      UPDATE: `${SYSTEM_BASE}/Menu/update`,
      DELETE_LIST: `${SYSTEM_BASE}/Menu/delete-list`,
      GET_LIST_BY_USER: `${SYSTEM_BASE}/Menu/get-list-by-user`,
    },
    Role: {
      GET_LIST: `${SYSTEM_BASE}/Role/get-list`,
      GET_BY_ID: `${SYSTEM_BASE}/Role/get-by-id`,
      INSERT: `${SYSTEM_BASE}/Role/insert`,
      UPDATE: `${SYSTEM_BASE}/Role/update`,
      DELETE_LIST: `${SYSTEM_BASE}/Role/delete-list`,
      GET_ALL_COMBOBOX: `${SYSTEM_BASE}/Role/get-all-combobox`,
      GET_PERMISSIONS_BY_ROLE: `${SYSTEM_BASE}/Role/get-permissions-by-role`,
      UPDATE_PERMISSIONS: `${SYSTEM_BASE}/Role/update-permissions`,
      GET_PERMISSIONS_BY_USER: `${SYSTEM_BASE}/Role/get-permissions-by-user`,
    },
    Auth: {
      LOGIN: `${SYSTEM_BASE}/Auth/login`,
      REFRESH_TOKEN: `${SYSTEM_BASE}/Auth/refresh-token`,
    },
  },
  Catalog: {
    Faculty: {
      GET_LIST: `${CATALOG_BASE}/Faculty/get-list`,
      GET_BY_ID: `${CATALOG_BASE}/Faculty/get-by-id`,
      INSERT: `${CATALOG_BASE}/Faculty/insert`,
      UPDATE: `${CATALOG_BASE}/Faculty/update`,
      DELETE_LIST: `${CATALOG_BASE}/Faculty/delete-list`,
      GET_ALL_COMBOBOX: `${CATALOG_BASE}/Faculty/get-all-combobox`,
    },
    Cycle: {
      GET_LIST: `${CATALOG_BASE}/Cycle/get-list`,
      GET_BY_ID: `${CATALOG_BASE}/Cycle/get-by-id`,
      INSERT: `${CATALOG_BASE}/Cycle/insert`,
      UPDATE: `${CATALOG_BASE}/Cycle/update`,
      DELETE_LIST: `${CATALOG_BASE}/Cycle/delete-list`,
      GET_COMBBOX_BY_USER: `${CATALOG_BASE}/Cycle/get-combobox-by-user`,
      CHANGE_STATUS: `${CATALOG_BASE}/Cycle/change-status`,
    },
    Stakeholder: {
      GET_LIST: `${CATALOG_BASE}/Stakeholder/get-list`,
      GET_BY_ID: `${CATALOG_BASE}/Stakeholder/get-by-id`,
      INSERT: `${CATALOG_BASE}/Stakeholder/insert`,
      UPDATE: `${CATALOG_BASE}/Stakeholder/update`,
      DELETE_LIST: `${CATALOG_BASE}/Stakeholder/delete-list`,
      GET_ALL_COMBOBOX: `${CATALOG_BASE}/Stakeholder/get-all-combobox`,
    },
    FileType: {
      GET_LIST: `${CATALOG_BASE}/FileType/get-list`,
      GET_BY_ID: `${CATALOG_BASE}/FileType/get-by-id`,
      INSERT: `${CATALOG_BASE}/FileType/insert`,
      UPDATE: `${CATALOG_BASE}/FileType/update`,
      DELETE_LIST: `${CATALOG_BASE}/FileType/delete-list`,
      GET_ALL_COMBOBOX: `${CATALOG_BASE}/FileType/get-all-combobox`,
    },
    Standard: {
      GET_LIST: `${CATALOG_BASE}/Standard/get-list`,
      GET_LIST_WITH_CRITERIA: `${CATALOG_BASE}/Standard/get-list-with-criteria`,
      GET_BY_ID: `${CATALOG_BASE}/Standard/get-by-id`,
      INSERT: `${CATALOG_BASE}/Standard/insert`,
      UPDATE: `${CATALOG_BASE}/Standard/update`,
      DELETE_LIST: `${CATALOG_BASE}/Standard/delete-list`,
      GET_ALL_COMBOBOX: `${CATALOG_BASE}/Standard/get-all-combobox`,
      GET_BY_STANDARD_SET_ID: `${CATALOG_BASE}/Standard/get-by-standard-set-id`,
    },
    StandardSet: {
      GET_LIST: `${CATALOG_BASE}/StandardSet/get-list`,
      GET_BY_ID: `${CATALOG_BASE}/StandardSet/get-by-id`,
      INSERT: `${CATALOG_BASE}/StandardSet/insert`,
      UPDATE: `${CATALOG_BASE}/StandardSet/update`,
      DELETE_LIST: `${CATALOG_BASE}/StandardSet/delete-list`,
      GET_ALL_COMBOBOX: `${CATALOG_BASE}/StandardSet/get-all-combobox`,
    },
  },
  Business: {
    Evidence: {
      GET_LIST: `${BUSINESS_BASE}/Evidence/get-list`,
      GET_BY_ID: `${BUSINESS_BASE}/Evidence/get-by-id`,
      INSERT: `${BUSINESS_BASE}/Evidence/insert`,
      UPDATE: `${BUSINESS_BASE}/Evidence/update`,
      DELETE_LIST: `${BUSINESS_BASE}/Evidence/delete-list`,
      GET_ALL_COMBOBOX: `${BUSINESS_BASE}/Evidence/get-all-combobox`,
    },
    EvidenceCycleMap: {
      GET_LIST: `${BUSINESS_BASE}/EvidenceCycleMap/get-list`,
      GET_BY_ID: `${BUSINESS_BASE}/EvidenceCycleMap/get-by-id`,
      INSERT_WITH_EVIDENCE: `${BUSINESS_BASE}/EvidenceCycleMap/insert-with-evidence`,
      UPDATE: `${BUSINESS_BASE}/EvidenceCycleMap/update`,
      DELETE_LIST: `${BUSINESS_BASE}/EvidenceCycleMap/delete-list`,
      GET_ALL_COMBOBOX: `${BUSINESS_BASE}/EvidenceCycleMap/get-all-combobox`,
    },
    SurveyTemplate: {
      GET_LIST: `${BUSINESS_BASE}/SurveyTemplate/get-list`,
      GET_BY_ID: `${BUSINESS_BASE}/SurveyTemplate/get-by-id`,
      INSERT: `${BUSINESS_BASE}/SurveyTemplate/insert`,
      UPDATE: `${BUSINESS_BASE}/SurveyTemplate/update`,
      DELETE_LIST: `${BUSINESS_BASE}/SurveyTemplate/delete-list`,
      GET_ALL_COMBOBOX: `${BUSINESS_BASE}/SurveyTemplate/get-all-combobox`,
    },
    SurveyCampaign: {
      GET_LIST: `${BUSINESS_BASE}/SurveyCampaign/get-list`,
      GET_BY_ID: `${BUSINESS_BASE}/SurveyCampaign/get-by-id`,
      INSERT: `${BUSINESS_BASE}/SurveyCampaign/insert`,
      UPDATE: `${BUSINESS_BASE}/SurveyCampaign/update`,
      DELETE_LIST: `${BUSINESS_BASE}/SurveyCampaign/delete-list`,
      GET_STAKEHOLDER_NOT_IN_CAMPAIGN: `${BUSINESS_BASE}/SurveyCampaign/get-stakeholder-not-in-campaign`,
      GET_LIST_SESSION: `${BUSINESS_BASE}/SurveyCampaign/get-list-session`,
      ADD_ALL_STAKEHOLDER_TO_CAMPAIGN: `${BUSINESS_BASE}/SurveyCampaign/add-all-stakeholder-to-campaign`,
      ADD_LIST_STAKEHOLDER_TO_CAMPAIGN: `${BUSINESS_BASE}/SurveyCampaign/add-list-stakeholder-to-campaign`,
      DELETE_LIST_SESSION: `${BUSINESS_BASE}/SurveyCampaign/delete-list-session`,
      CHANGE_STATUS: `${BUSINESS_BASE}/SurveyCampaign/change-status`,
      SEND_SURVEY_INVITATION: `${BUSINESS_BASE}/SurveyCampaign/send-survey-invitation`,
      GET_SURVEY_BY_TOKEN: `${BUSINESS_BASE}/SurveyCampaign/get-survey-by-token`,
      SUBMIT_SURVEY: `${BUSINESS_BASE}/SurveyCampaign/submit-survey`,
    },
  },
  File: {
    UploadFile: {
      POST: `${FILE_BASE}/api/UploadFile`,
      GET: `${FILE_BASE}/`,
    },
  },
};
