import { useState, useMemo } from "react";
import type { RowSelectionState } from "@tanstack/react-table";
import { Button } from "@/components/ui/Button";
import { DataTable } from "./data-table";
import { getSessionColumns } from "./session-columns";
import { PopupStakeholderSelection } from "./PopupStakeholderSelection";
import type { SurveySession } from "../../../types/survey-campaign.types";

interface StakeholderSelectorProps {
  stakeholderType: string;
  selectedSessions: SurveySession[];
  onSelectionChange: (selectedSessions: SurveySession[]) => void;
}

export const StakeholderSelector = ({
  stakeholderType,
  selectedSessions,
  onSelectionChange,
}: StakeholderSelectorProps) => {
  const [rowSelection, setRowSelection] = useState<RowSelectionState>({});
  const [isPopupOpen, setIsPopupOpen] = useState(false);

  // Columns for the selected list
  const columns = useMemo(() => getSessionColumns(), []);

  // DELETE handler
  const handleDelete = () => {
    const selectedIndices = Object.keys(rowSelection).filter(
      (key) => rowSelection[key],
    );

    // Create a new list excluding the selected indices
    // Note: rowSelection keys are indices in the current data array (which is selectedSessions)
    const newSessions = selectedSessions.filter(
      (_, index) => !rowSelection[parseInt(index.toString())],
    );

    onSelectionChange(newSessions);
    setRowSelection({}); // Reset selection
  };

  // ADD handler (from popup)
  const handleAdd = (selectedStakeholders: any[]) => {
    const newSessions = selectedStakeholders.map(
      (stakeholder) =>
        ({
          Id: "", // will be generated by backend or UUID if needed
          CampaignId: "", // will be set by parent
          StakeholderId: stakeholder.Id,
          StakeholderName: stakeholder.FullName,
          StakeholderEmail: stakeholder.Email,
          Status: 0, // Default status
        }) as SurveySession,
    );

    onSelectionChange([...selectedSessions, ...newSessions]);
  };

  if (!stakeholderType) {
    return (
      <div className="flex items-center justify-center h-48 border rounded-lg bg-gray-50 text-gray-500">
        Vui lòng chọn Loại đối tượng ở tab Thông tin chung trước.
      </div>
    );
  }

  const hasSelection = Object.keys(rowSelection).some(
    (key) => rowSelection[key],
  );

  return (
    <div className="space-y-4">
      <div className="flex items-center space-x-2">
        <Button type="button" size="sm" onClick={() => setIsPopupOpen(true)}>
          Thêm
        </Button>

        <Button
          type="button"
          size="sm"
          variant="destructive"
          onClick={handleDelete}
          disabled={!hasSelection}
        >
          Xóa
        </Button>
      </div>

      <div className="rounded-md border bg-white">
        <DataTable
          columns={columns}
          data={selectedSessions}
          rowSelection={rowSelection}
          onRowSelectionChange={setRowSelection}
        />
      </div>

      <PopupStakeholderSelection
        open={isPopupOpen}
        onOpenChange={setIsPopupOpen}
        stakeholderType={stakeholderType}
        onSelect={handleAdd}
        excludeIds={selectedSessions.map((s) => s.StakeholderId)}
      />
    </div>
  );
};
