syntax = "proto3";

option csharp_namespace = "AUN_QA.SystemService.Protos";

package system;

service SystemProto {
  rpc CheckPermission (CheckPermissionRequest) returns (CheckActionResponse);
  rpc GetUsersByIds (GetUsersByIdsRequest) returns (GetUsersByIdsResponse);
  rpc GetUsersByUsernames (GetUsersByUsernamesRequest) returns (GetUsersByUsernamesResponse);
  rpc SetUsersActived (SetUsersActivedRequest) returns (SetUsersActivedResponse);
  rpc CreateExternalUser (CreateExternalUserRequest) returns (CreateExternalUserResponse);
}

message CheckPermissionRequest {
  string user_id = 1;
  string controller = 2;
  int32 action = 3;
}

message CheckActionResponse {
  bool success = 1;
}

message GetUsersByIdsRequest {
  repeated string user_ids = 1;
}

message UserInfo {
  string id = 1;
  string fullname = 2;
  string avatar = 3;
  string username = 4;
  bool is_actived = 5;
}

message GetUsersByIdsResponse {
  repeated UserInfo users = 1;
}

message GetUsersByUsernamesRequest {
  repeated string usernames = 1;
}

message GetUsersByUsernamesResponse {
  repeated UserInfo users = 1;
}

message SetUsersActivedRequest {
  repeated string user_ids = 1;
  bool is_actived = 2;
}

message SetUsersActivedResponse {
  bool success = 1;
}

message CreateExternalUserRequest {
  string fullname = 1;
  string username = 2;
  string email = 3;
  string password = 4;
  string role_id = 5;
}

message CreateExternalUserResponse {
  string id = 1;
  bool success = 2;
  string message = 3;
}
