syntax = "proto3";

import "google/protobuf/wrappers.proto";
import "google/protobuf/timestamp.proto";

option csharp_namespace = "AUN_QA.CatalogService.Protos";

package catalog;

service CatalogProto {
  rpc GetStakeholdersStream (GetStakeholdersStreamRequest) returns (stream StakeholderInfo);
  rpc GetCyclesStream (GetCyclesStreamRequest) returns (stream CycleInfo);
  rpc GetCriterionsForEvidenceStream (GetCriterionsForEvidenceStreamRequest) returns (stream CriterionInfo);

  rpc IsUserInRole (IsUserInRoleRequest) returns (google.protobuf.BoolValue);
  rpc GetUserRole (GetUserRoleRequest) returns (google.protobuf.Int32Value);
  rpc GetFileTypesStream (GetFileTypesStreamRequest) returns (stream FileTypeInfo);

  rpc CanUserDoActionInPdca (CanUserDoActionInPdcaRequest) returns (google.protobuf.BoolValue);
  rpc GetCycleIdsByUser (GetCycleIdsByUserRequest) returns (CycleIdsByUserResponse);
  rpc GetCycleStatus (GetCycleStatusRequest) returns (GetCycleStatusResponse);
}

message GetStakeholdersStreamRequest {
  google.protobuf.StringValue id = 1;
  google.protobuf.Int32Value stakeholder_type = 2;
}

message StakeholderInfo {
  string id = 1;
  string full_name = 2;
  string email = 3;
  int32 type = 4;
  string description = 5;
}

message GetCyclesStreamRequest {
  google.protobuf.Int32Value year = 1;
}

message CycleInfo {
  string id = 1;
  string name = 2;
  int32 year = 3;
  google.protobuf.Timestamp start_date = 4;
  google.protobuf.Timestamp end_date = 5;
  int32 status = 6;
  string evaluation_purpose = 7;
  int32 scope = 8;
}

message IsUserInRoleRequest {
  string cycle_id = 1;
  string user_id = 2;
  int32 role = 3;
}

message GetUserRoleRequest {
  string cycle_id = 1;
  string user_id = 2;
}

// Standard service
message CriterionInfo {
  string id = 1;
  string standard_id = 2;
  string code = 3;
  string name = 4;
  bool is_prerequisite = 5;
  string diagnostic_questions = 6;
  string description = 7;
  int32 order = 8;
}

message GetCriterionsForEvidenceStreamRequest {
  string file_type_id = 1;
  string cycle_id = 2;
}

// FileType
message FileTypeInfo {
  string id = 1;
  string code = 2;
  string name = 3;
  optional string description = 4;
}

message GetFileTypesStreamRequest {
  google.protobuf.StringValue id = 1;
}

// PDCA Permission Check
message CanUserDoActionInPdcaRequest {
  string user_id = 1;
  string cycle_id = 2;
  google.protobuf.StringValue standard_id = 4; // optional
  repeated int32 allowed_roles = 5;
}

message GetCycleIdsByUserRequest {
  string user_id = 1;
}

message CycleIdsByUserResponse {
  repeated string cycle_ids = 1;
}

// Cycle Status Check
message GetCycleStatusRequest {
  string cycle_id = 1;
}

message GetCycleStatusResponse {
  bool found = 1;
  int32 status = 2;
}